--INSERT INTO member (id,name) VALUES (1,'name1')
--INSERT INTO member (id,name) VALUES (2,'name2')
--INSERT INTO member (id,name) VALUES (3,'name3')
INSERT INTO article (title,content) VALUES ('제목 1','내용 1')
INSERT INTO article (title,content) VALUES ('제목 2','내용 2')
INSERT INTO article (title,content) VALUES ('제목 3','내용 3')
